### PR TITLE
[feature request] Add `clump_from` (or similar api)

### PR DESCRIPTION
**Pull request by agathazeren**
This function cannot be implemented with the existing api without iterating linearly through part of the set, but is a useful feature of a ranged set. 

I'm not attached to the api or the name. Some alternatives are:
 - A cursor api (though implementing this efficiently requires the `btree_cursors` feature to be stabilized)
 - returning a range instead of a length as the second tuple member
 - returning a struct instead of a tuple
 - `fn range_of(&self, value: T) -> Option<Range<T>>` and `fn gap_of(&self, value: T) -> Option<Range<T>>`
 - additionally implementing `clump_to` and `clump_at` with the same api
 
 Update: I have now used this api for a bit and decided I don't like it, but am not sure what to replace it with. The problem is that it has the case `(true, None)` which should be be possible. The problem with changing the output type to `Option<(bool, T::SafeLen)>` is that then it does not destructure as cleanly when you first need to act on whether it was contained or not.

I'm leaning towards a custom clump type being the cleanest option here, but it significantly adds to the api surface.
```rust
pub enum Clump {
    /// An inclusive range
    pub Range(T, T),
    /// An inclusive or (on the right) unbounded range
    pub Gap(T, Option<T>),
}
```

### CODE REVIEW

**Comment by CarlKCarlK** [comment]
Agatha,

Thanks for using range-set-blaze!

I'm traveling at it may be a couple of weeks before I can look at this in depth.

My first impression is that I like the range_of, gap_of API because they clearly return a new range, which would allow the existing range to mutate as other integers were added/deleted.

How do you imagine using this? Can you give a little example? (The only thing I can think of is uses the ranges as the keys in map, which I don't know that I'd recommend.)

Finally, can you give me more details on what clump_to and clump_at would do?

Thanks again for your interest in range-set-blaze,

Carl

From: Agatha Zeren ***@***.***>
Sent: Sunday, October 08, 2023 12:07 AM
To: CarlKCarlK/range-set-blaze ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CarlKCarlK/range-set-blaze] [feature request] Add `clump_from` (or similar api) (PR #11)


This function cannot be implemented with the existing api without iterating linearly through part of the set, but is a useful feature of a ranged set.

I'm not attached to the api or the name. Some alternatives are:

  *   A cursor api (though implementing this efficiently requires the btree_cursors feature to be stabilized)
  *   returning a range instead of a length as the second tuple member
  *   returning a struct instead of a tuple
  *   fn range_of(&self, value: T) -> Option<Range<T>> and fn gap_of(&self, value: T) -> Option<Range<T>>
  *   additionally implementing clump_to and clump_at with the same api

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/CarlKCarlK/range-set-blaze/pull/11

Commit Summary

  *   71ec951<https://github.com/CarlKCarlK/range-set-blaze/pull/11/commits/71ec9516ea800a2d602bd0a9626fa5657e330e03> Add `clump_from`

File Changes

(1 file<https://github.com/CarlKCarlK/range-set-blaze/pull/11/files>)

  *   M src/lib.rs<https://github.com/CarlKCarlK/range-set-blaze/pull/11/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759> (47)

Patch Links:

  *   https://github.com/CarlKCarlK/range-set-blaze/pull/11.patch
  *   https://github.com/CarlKCarlK/range-set-blaze/pull/11.diff

-

**Comment by CarlKCarlK** [comment]
Agatha,

How about
* Just like there is currently a notion of ranges (used by `ranges`, `ranges_len`, and `ranges_insert`) we define a notion of `Rog` for range or gap.

```
/// Enum to represent either a range or a gap.
#[derive(Debug, PartialEq, Eq)]
pub enum Rog<T: Integer> {
    Range(RangeInclusive<T>),
    Gap(RangeInclusive<T>),
}
```

* Just like `RangeSetBlaze` and `BTreeSet` currently have a `range` method (not to be confused with the `ranges` method) that gives an iterator of integers within a range, we define a new rog_range that returns the gaps and ranges with in a range.

* Here is what use could look like:

```
    #[test]
    fn test_rog_functionality() {
        let a = RangeSetBlaze::from_iter([1..=6, 8..=9, 11..=15]);
        let rri = a.rog_range(10..=20);
        assert!(rri.next(), Some(Rog::Gap(10..=10)));
        assert!(rri.next(), Some(Rog::Range(11..=15)));
        assert!(rri.next(), Some(Rog::Gap(16..=20)));
        assert!(rri.next(), None);
    }
```

* This would be available as an optional feature called 'rog-experimental`.

* Later things that could be added would be `rog_len`, `rog`, (maybe) `rog_insert`. Also, we should eventually add `ranges_range`.

Let me know what you think.

- Carl

**Comment by agathazeren** [comment]
> Just like there is currently a notion of ranges (used by ranges, ranges_len, and ranges_insert) we define a notion of Rog for range or gap.

This is the clump-based api I proposed above. I am not a big fan of this name `Rog`, so here are few more colors for the bike shed but I'll go for what you want.

 - `Rog`
 - `Clump`
 - `Part`
 - `Group`
 - `Sequence`
 - `Portion`
 - `Area`
 - `Continuous` 
 
> Just like RangeSetBlaze and BTreeSet currently have a range method (not to be confused with the ranges method) that gives an iterator of integers within a range, we define a new rog_range that returns the gaps and ranges with in a range.

This makes sense, and would be sufficient for the use case.

There is one use case that is not covered by this, which is finding the `Rog` surrounding a given point, but I would not like to hold up this over it.

> This would be available as an optional feature called 'rog-experimental`.

Are you thinking of using the pattern of not declaring it as a feature in cargo, but instead requiring `--cfg range_set_blaze_unstable_rog` (modulo naming) in order to make the instability viral, or just document that enabling the cargo feature transitively breaks semver?


> Later things that could be added would be rog_len, rog, (maybe) rog_insert.

Makes sense.
    
> Also, we should eventually add ranges_range.

Also seems like it follows.

I'll get started on the implementation soon.

**Comment by CarlKCarlK** [comment]
Agatha,


  *   This is the clump-based api I proposed above
Just so.

I’d prefer to do implementation (unless you have your heart set on it). It’s very similar to the “internal_add” code that I recently did a formal analysis of<https://medium.com/towards-data-science/nine-rules-to-formally-validate-rust-algorithms-with-dafny-part-2-f2a279686700>. It should just take a day or two.

I ended up with “Rog” because names like “clump” don’t seem distinct from “range”. With C#, I would have spelled it out and called it “RangeOrGap” but Rust doesn’t seem to mind abbreviations as much as C#
(I think). Also, I thought that “rog_range” was easier method name to remember and understand compared to “range_or_gap_range”, etc.

Now, I’m wondering if the method should be plural “rogs_range” because the current methods are “ranges_len” “ranges”, and “ranges_insert”.


  *   There is one use case that is not covered by this, which is finding the Rog surrounding a given point, but I would not like to hold up this over it.
Good point. How about also a method called ”rogs_get”? It would return a Rog. There could also be a “ranges_get” that returns a Optional<InclusiveRange>.. (BTreeSet has a ‘get’ method that returns an Optional<T>)


  *   Are you thinking of using the pattern of not declaring it as a feature in cargo, but instead requiring --cfg range_set_blaze_unstable_rog (modulo naming) in order to make the instability viral, or just document that enabling the cargo feature transitively breaks semver?
I not thought about this. I’d prefer to just document it. (I may not be as sensitive semver as I should be 😊.)



  *   Carl

**Comment by agathazeren** [comment]
Sounds good.

**Comment by CarlKCarlK** [comment]
@agathazeren

I think I have something for you to try:

In your Cargo.toml:

```
[dependencies]
range-set-blaze = { version = "0.1.13-beta.3", features = ["rog-experimental"] }
```
Here is a sample main.rs (notice the #![allow(deprecated)]):

```
#![allow(deprecated)]
use range_set_blaze::{RangeSetBlaze, Rog};
use std::ops::Bound::Included;

fn main() {
    let mut set = RangeSetBlaze::new();
    set.insert(3);
    set.insert(5);
    set.insert(6);
    for rog in set.rogs_range((Included(4), Included(8))) {
        println!("{rog:?}");
    } // prints: Gap(4..=4)\nRange(5..=6)\nGap(7..=8)

    assert_eq!(Some(Rog::Gap(4..=4)), set.rogs_range(4..).next());

    let a = RangeSetBlaze::from_iter([1..=6, 11..=15]);
    assert_eq!(
        a.rogs_range(-5..=8).collect::<Vec<_>>(),
        vec![Rog::Gap(-5..=0), Rog::Range(1..=6), Rog::Gap(7..=8)]
    );

    let empty = RangeSetBlaze::<u8>::new();
    assert_eq!(
        empty.rogs_range(..).collect::<Vec<_>>(),
        vec![Rog::Gap(0..=255)]
    );

    // rogs_get
    let range_set_blaze = RangeSetBlaze::from([1, 2, 3]);
    assert_eq!(range_set_blaze.rogs_get(2), Rog::Range(1..=3));
    assert_eq!(range_set_blaze.rogs_get(4), Rog::Gap(4..=2_147_483_647));
}
```

There is documentation at https://docs.rs/range-set-blaze/0.1.13-beta.3/range_set_blaze/index.html.

Notes:
* I marked the experimental stuff "deprecated" which seemed clever at the time but now is a bit annoying.
* Some links in the new beta documentation point to the main documentation (especially in the first section). If that happens, back up and try to navigate other ways.
* Source code is on the "oct23" branch, https://github.com/CarlKCarlK/range-set-blaze/tree/oct23
* As discussed, the methods are O(ln #clumps) to start and then constant time.
* You can see the tests at https://github.com/CarlKCarlK/range-set-blaze/blob/18a67267b19e776bd7509be9fd629d4540beee61/tests/integration_test.rs#L1491. Most of the tests compare the fast methods to hidden slow-but-more-obvious methods and verify the results are the same.

Let me know if this does what you need.

- Carl

**Comment by agathazeren** [comment]
I've been rather busy with school and life so have not had a time to integrate this api into my project, but I am pretty sure that it should work for me based on your description.

Thanks for the work on this!
--Agatha

**Comment by CarlKCarlK** [comment]
Excellent!

**Comment by CarlKCarlK** [comment]
The Rog features are now on crates.io was v0.1.13. They are no longer beta but are still optional and marked "deprecated". Again, thanks for the great suggestion.

**Comment by CarlKCarlK** [comment]
@agathazeren Just a heads up that the gaps and ranges functions are now in the main release (0.7.0). They are changed from the previous gated/experimental Rog version, but I think better. See
https://docs.rs/range-set-blaze/latest/range_set_blaze/gaps/index.html
for examples.

**Pull request closed without merging**
